name       : noisetorch
version    : 0.11.5
release    : 2
source     :
    - https://github.com/lawl/NoiseTorch/archive/refs/tags/0.11.5.tar.gz : cae2f9ee51bf1fc5a8bfe66cddd89b4ca9b79234f8664a7549ee08b453326501
license    : GPL-3.0-only
component  : multimedia.audio
summary    : Virtual microphone noise suppressor
description: |
    NoiseTorch is an easy to use open source application for Linux with PulseAudio or PipeWire. It creates a virtual microphone that suppresses noise, in any application. Use whichever conferencing or VOIP application you like and simply select the NoiseTorch Virtual Microphone as input to torch the sound of your mechanical keyboard, computer fans, trains and the likes.
builddeps  :
    - golang
build      : |
    %make VERSION=$version
install    : |
    install -dm00755 $installdir/usr/bin/
    install -dm00755 $installdir/usr/share/applications/
    install -dm00755 $installdir/usr/share/icons/hicolor/256x256/apps/
    install -Dm00755 $workdir/bin/noisetorch $installdir/usr/bin/
    install -Dm00644 $workdir/assets/noisetorch.desktop $installdir/usr/share/applications/
    install -Dm00644 $workdir/assets/icon/noisetorch.png $installdir/usr/share/icons/hicolor/256x256/apps/
